


// Write a function doubleSequence that accepts a base and a Length as arguments.
// The function should return an array representing a sequence that contains "Length" elements.
// The first element of the sequence is always the "base", the subsequent elements can be
// generated by doubling the previous element of the sequence.


function doubleSequence(base, length){
    let newArr = [base];

    if(length === 0) return [];

    for(let i = 0; i < length-1; i++){
        let lastElem = newArr[newArr.length - 1];
        let nextElem = lastElem * 2;
        newArr.push(nextElem);
    }   
    
    return newArr;
}




console.log(doubleSequence(7, 3));                  // [7, 14, 28]
console.log(doubleSequence(3, 5));                  // [3, 6, 12, 24, 48]
console.log(doubleSequence(5, 3));                  // [5, 10, 20]
console.log(doubleSequence(5, 4));                  // [5, 10, 20, 40]
console.log(doubleSequence(5, 0));                  // []